### ISSUE TITLE
[예외처리] 나라 선택

### ISSUE THREAD

**Issue by Hwna** [Hwna/2020-02-ADProject#3]
시작하는 나라와 끝나는 나라가 같은 상황에 대한 예외 처리가 필요할 것 같습니다. 에러가 발생하지는 않지만 적절한 조치를 생각해보면 좋을 것 같습니다.

나라를 선택하지 않고 기본 값인 "국가 선택"으로 되어 있는 상황에 대해서도 예외처리가 필요합니다.

**Comment by miten267** [comment]
PyQt에 버튼 setEnable 이라는기능이 있던데 이 기능을 쓰면 버튼이 눌리지 않게 만들 수 있답니다.  국가선택 두개를 해야 한 뒤에 이 값을 True 로 바꿔서 버튼이 클릭 가능하게 설정하면 어떨까요? https://wikidocs.net/21934 여기 보시면 이해가 더 편하실 겁니다.

**Comment by Hwna** [comment]
저는 사실 국가 선택을 선택한 채로 환전을 시도하면 alert창 같은 걸 띄어보려고 했는데 말씀해주신 방법도 좋은 것 같아요.
한 번 찾아보고 고쳐볼게요
