### ISSUE TITLE
[예외 처리] 나라를 선택했다가 다시 '국가 선택' 을 선택할때

### ISSUE THREAD

**Issue by miten267** [Hwna/2020-02-ADProject#4]
무슨 이유에서 인지는 모르겠지만 나라를 선택했다가 다시 국가선택으로 잘못 클릭하면 프로그램이 강제종료 되네요. 어떻게 해야 좋을까요?

**Comment by Hwna** [comment]
콤보 박스에서 선택한 값을 기준으로 국가 아이콘을 가져오기 때문인 것 같습니다.
국가 선택을 없애던가 아니면 따로 예외처리를 하면 될 것 같습니다.
